// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evrpmxgrdbmafrhlkrka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cnBteGdyZGJtYWZyaGxrcmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NTYyMDcsImV4cCI6MjA1ODUzMjIwN30.1KpdyWVBMQrno2qlntAw7_BpAFB_t8821hluGoRXw1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);